### ISSUE TITLE
available database

### ISSUE THREAD

**Issue by alpapan** [soedinglab/uniclust-pipeline#8]
Hello guys

Main question:
What would be the recommended way / database to search a protein against UniprotKB therefore?

The reason I'm asking is because:
1) I'm currently confused which UniprotKB database to use with HHBlits v3.

The http://wwwuser.gwdg.de/~compbiol/uniclust/2018_08/ only has the HHsearch version with a3m format, not ca3m. The most recent 'uniboost' database is from 2016.

2) Also, to detect homology, should we be using mmseq or hhblits (i've been using the former for the past 3 years, only used mmseq to make my own hhblits-compatible databases).

3) I tried to use HHblits with http://wwwuser.gwdg.de/~compbiol/uniclust/2018_08/uniclust30_2018_08_hhsuite.tar.gz but I got far fewer hits than I'm used to a year ago

any advice, greatly appreciated
a

**Comment by milot-mirdita** [comment]
Hi Alexie,

For completeness sake, I'll also answer here:

1. You should be using the Uniclust30. For the Uniclust there ca3m format would not offer any benefit (even slow it down). That is only required for the Uniboost.
2. Depends on your use case. MMseqs2 is magnitudes faster, but cannot reach the sensitivity that HHblits offers. If you have only a few hundred sequences to annotate, HHblits will serve you well. For more, MMseqs2 will be your best bet. Since it reaches BLAST or PSI-BLAST level sensitivity at a fraction of their runtime (and also HHblits' runtime).
3. Our regression test did not complain about the release. Something might still be wrong of course. Can you provide us with more details please?
